project:
  type: website

website:
  title: "Alex J. Tovar"
  description: "Data Scientist"
  navbar:
    left:
      - href: index.qmd
        text: "Car Crash Detector"
      - text: "A/B TESTING"
        menu:
          - href: AB_TESTS/MyTwoWayANOVA.Rmd
            text: "Two-way ANOVA"
          - href: AB_TESTS/MyChiSquaredTest.Rmd
            text: "Chi-Squared Test"
          - href: AB_TESTS/MyLogisticRegression.Rmd
            text: "Logistic Regression"
          - href: AB_TESTS/HighSchoolSeniors.Rmd
            text: "T-test"
          - href: AB_TESTS/RecallingWords.Rmd
            text: "Wilcoxon Rank Sum (Mann–Whitney) test"
      - text: "Projects"
        menu:
          - href: Projects\NFL\NFL.Rmd
            text: "NFL Data Analysis"
      - text: "Blogs"
        menu:
          - href: Blogs/Linkedin_Reach_Tips.Rmd
            text: "Linkedin Reach Tips"
          - href: Blogs/Hosting_Using_AWS.Rmd
            text: "Hosting Using AWS" 
          - href: Blogs/AWS_Cloud_Computing.Rmd
            text: "AWS Cloud Computing"


format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



