project:
  type: website

website:
  title: "Alex J. Tovar"
  description: "Data Scientist"
  navbar:
    left:
      - href: index.qmd
        text: "Wrecked Car Detector"
      - text: "A/B TESTING"
        menu:
          - href: AB_TESTS/MyTwoWayANOVA.Rmd
            text: "Two-way ANOVA"
          - href: AB_TESTS/MyChiSquaredTest.Rmd
            text: "Chi-Squared Test"
          - href: AB_TESTS/MyLogisticRegression.Rmd
            text: "Logistic Regression"
          - href: AB_TESTS/HighSchoolSeniors.Rmd
            text: "T-test"
          - href: AB_TESTS/RecallingWords.Rmd
            text: "Wilcoxon Rank Sum (Mann–Whitney) test"
      - text: "Projects"
        menu:
          - href: Projects\NFL\NFL.Rmd
            text: "NFL Data Analysis"
      - text: "Blogs"
        menu:
          - href: Blogs/Linkedin_Reach_Tips.Rmd
            text: "Linkedin Reach Tips"
          - href: Blogs/Hosting_Using_AWS.Rmd
            text: "Hosting Using AWS" 
          - href: Blogs/AWS_Cloud_Computing.Rmd
            text: "AWS Cloud Computing"
          - href: Blogs/End-to-End_ML.Rmd
            text: "End-to-End ML Applications"
          - href: Blogs/My_First_Week.Rmd
            text: "First Week in Entrepreneurship"
          - href: Blogs/post2.Rmd
            text: "The Importance of Dreams"
          - href: Blogs/LaunchingLeaders.Rmd
            text: "Launching Leaders"
          - href: Blogs/HeroJourney.Rmd
            text: "Hero's Journey Talk"
          - href: "Blogs/Three.Rmd"
            text: "Three Entrepreneurs"
          - href: "Blogs/7lessons.Rmd"
            text: "Lessons From Effective People"
          - href: "Blogs/perseverance.Rmd"
            text: "Lessons of Perseverance"
          - href: "Blogs/Ethics.Rmd"
            text: "Ethics & Greatness"
          - href: "Blogs/BigDreams.Rmd"
            text: "Big Dreams"
          - href: "Blogs/Measuring.Rmd"
            text: "Measuring Success"


format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



